# Generated by Django 4.2.5 on 2023-10-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_rename_description_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
    ]
