# Generated by Django 4.2.5 on 2023-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=50, unique=True),
        ),
    ]
