# Generated by Django 4.2.5 on 2023-10-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_author_remove_post_author_name_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
