# Generated by Django 4.2.5 on 2023-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_remove_post_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
