# Generated by Django 4.2.5 on 2023-10-05 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='quantity',
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
