# Generated by Django 4.2.5 on 2023-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_post_post_type_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2),
        ),
    ]
